name: 刷步数

on:
  push:
    branches: [ mian ]
  schedule:
    - cron: 05 2 * * *


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 开始
        run: |
          pip install requests
          pmode='${{ secrets.PMODE }}'
          pkey='${{ secrets.PKEY }}'
          user='${{ secrets.USER }}'
          pwd='${{ secrets.PWD }}'
          step='${{ secrets.STEP }}'

          python3 main.py ${pmode} ${pkey} ${user} ${pwd} ${step}
